name: ci-js-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run application
        run: npm start